const bgStylePokemonType = {
  grass: "bg-gradient-to-b from-grass/90 to-grass/30",
  water: "bg-gradient-to-b from-water/90 to-water/30",
  normal: "bg-gradient-to-b from-normal/90 to-normal/30",
  fighting: "bg-gradient-to-b from-fighting/90 to-fighting/30",
  flying: "bg-gradient-to-b from-flying/90 to-flying/30",
  poison: "bg-gradient-to-b from-poison/90 to-poison/30",
  ground: "bg-gradient-to-b from-ground/90 to-ground/30",
  rock: "bg-gradient-to-b from-rock/90 to-rock/30",
  bug: "bg-gradient-to-b from-bug/90 to-bug/30",
  ghost: "bg-gradient-to-b from-ghost/90 to-ghost/30",
  steel: "bg-gradient-to-b from-steel/90 to-steel/30",
  fire: "bg-gradient-to-b from-fire/90 to-fire/30",
  electric: "bg-gradient-to-b from-electric/90 to-electric/30",
  psychic: "bg-gradient-to-b from-psychic/90 to-psychic/30",
  ice: "bg-gradient-to-b from-ice/90 to-ice/30",
  dragon: "bg-gradient-to-b from-dragon/90 to-dragon/30",
  dark: "bg-gradient-to-b from-dark/90 to-dark/30",
  fairy: "bg-gradient-to-b from-fairy/90 to-fairy/30",
  unknown: "bg-gradient-to-b from-unknown/90 to-unknown/30",
  shadow: "bg-gradient-to-b from-shadow/90 to-shadow/30",
};

const borderStyledPokemonByType = {
  grass: "border-[5px] border-grass",
  water: "border-[5px] border-water",
  normal: "border-[5px] border-normal",
  fighting: "border-[5px] border-fighting",
  flying: "border-[5px] border-flying",
  poison: "border-[5px] border-poison",
  ground: "border-[5px] border-ground",
  rock: "border-[5px] border-rock",
  bug: "border-[5px] border-bug",
  ghost: "border-[5px] border-ghost",
  steel: "border-[5px] border-steel",
  fire: "border-[5px] border-fire",
  electric: "border-[5px] border-electric",
  psychic: "border-[5px] border-psychic",
  psychic: "border-[5px] border-psychic",
  ice: "border-[5px] border-ice",
  dragon: "border-[5px] border-dragon",
  fairy: "border-[5px] border-fairy",
  unknown: "border-[5px] border-unknown",
  shadow: "border-[5px] border-grashadowss",
};

const textStyledPokemonByType = {
  grass: "text-grass",
  water: "text-water",
  normal: "text-normal",
  fighting: "text-fighting",
  flying: "text-flying",
  poison: "text-poison",
  ground: "text-ground",
  rock: "text-rock",
  bug: "text-bug",
  ghost: "text-ghost",
  steel: "text-steel",
  fire: "text-fire",
  electric: "text-electric",
  psychic: "text-psychic",
  ice: "text-ice",
  dragon: "text-dragon",
  fairy: "text-fairy",
  unknown: "text-unknown",
  shadow: "text-shadow",
};

export {
  bgStylePokemonType,
  borderStyledPokemonByType,
  textStyledPokemonByType,
};
